### ISSUE TITLE
Blog images are enlarged to full width on Firefox

### ISSUE THREAD

**Issue by JohnLZeller** [SpaceAdvocates/penny4nasa#28]
Blog images are looking crazy here on Firefox: http://penny4nasa.cloudcontrolled.com/after-chelyabinsk-meteor-strike-nasa-ramps-up-asteroid-detection-efforts/

The image is full width and pushed to the right making it totally obstruct the right side bar

**Comment by josephspens** [comment]
I haven't uploaded the latest code to cloudcontrolled yet, should be fixed though.

**Comment by JohnLZeller** [comment]
Looks like this is still happening with the most recent tip of this repo.
Bug is present in both Firefox and Chrome.

![](http://s30.postimg.org/njl2nnjjl/Screen_Shot_2014_04_15_at_11_40_59_AM.png)

**Comment by josephspens** [comment]
That happens because that image is in the blog post itself, it's not set as the featured image.

We need to go through all the posts and remove these images from the top of the post body and set them as the featured images.

**Comment by JohnLZeller** [comment]
What happens when an author wants to embed a photo in the text? Asking for documentations sake.

**Comment by josephspens** [comment]
Take a look at the post Light Pollution and NASA: Combating the “Dark Side” of Light

**Comment by JohnLZeller** [comment]
Okay, excellent :) Thanks for the info!
